config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resource :sessions, only: [:new, :create, :destroy]
  resources :applicants
  resources :pages

  get 'sessions/create'
  post 'sessions/create'
  delete 'pages' => 'pages#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/film.rb
class Film < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true

  def password=(pwd)
    generated_password(pwd)
  end

  def self.authenticated?(username, password)
    user = User.find_by_username(username)
    if user && Digest::SHA256.hexdigest(password + user.salt) == user.hashed_password
      user
    else
      false
    end
  end

  private

  def generated_password(pwd)
    self.salt = Array.new(10) { rand(1024).to_s(36) }.join
    self.hashed_password = Digest::SHA256.hexdigest(pwd + salt)
  end
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:notice] = 'Successfully registered.'
      redirect_to new_sessions_path
    else
      redirect_to new_applicant_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if params[:order_by]
      @films = Film.paginate(page: params[:page], per_page: 20).order(params[:order_by] + ' DESC')
    else
      @films = Film.paginate(page: params[:page], per_page: 20)
    end
  end

  def destroy
    @film = Film.find(params[:id])
    @film.destroy
    redirect_to pages_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    if params[:username] == 'admin' && params[:password] == 'admin' # 验证是否管理员登陆
      session[:admin] = true
      redirect_to pages_path
    else
      @user = User.authenticated?(params[:username], params[:password])
      if @user
        redirect_to pages_path
        flash[:notice] = "Welcome, #{@user.username}"
      else
        redirect_to new_sessions_path
        flash[:notice] = 'Invalid username or password!'
      end
    end
  end

  def destroy
    session.delete(:admin)
    redirect_to new_sessions_path
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/applicants/new.html.erb
<h1>Sign up</h1>
<%= flash[:error] %>

<%= form_for @user, url: :applicants do |f| %>
	<%= f.label "Username:" %>
	<%= f.text_field :username %>
	<%= f.label "Password:" %>
	<%= f.password_field :password %>
	<%= f.submit "Signup" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrawlerByRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div style="text-align:center">
	<h1 style="color:red">MOVIE</h1>

	<%= link_to "按时间排序", pages_url(order_by: :date) %>
	<%= link_to "按评分排序", pages_path(order_by: :rate ) %>

	<div class='films' >
		<table style="margin: 0 auto">
			<tr>
        <th>Name</th>
        <th>category</th>
        <th>date</th>
        <th>rate</th>			
			</tr>

			<% @films.each do |film| %>
				<tr>
					<td><%= film.name %></td>
					<td><%= film.category %></td>
					<td><%= film.date %></td>
					<td><%= film.rate %></td>			
					<td><%= link_to "delete", pages_path(id: film.id), method: :delete, data: { confirm: 'Are You Sure?' } if session[:admin] %></td>
		 	</tr>		
			<%end%>
		</table>
		<%= will_paginate @films %>
	</div>

	<%= link_to "Log out", sessions_path, method: :delete %>
</div>